// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package misc

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Base(comp templ.Component, showNav bool) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><title></title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><style>\n\t\t\t\t[x-cloak] { \n\t\t\t\t\tdisplay: none !important;\n\t\t\t\t\t}\n\t\t\t\t.htmx-indicator{\n\t\t\t\t\tdisplay:none !important;\n\t\t\t\t\t}\n\t\t\t\t.htmx-request .htmx-indicator{\n\t\t\t\t\tdisplay:inline !important;\n\t\t\t\t\t}\n\t\t\t\t.htmx-request.htmx-indicator{\n\t\t\t\t\tdisplay:inline !important;\n\t\t\t\t\t}\n\t\t\t</style><link href=\"/static/output.css\" rel=\"stylesheet\"><script src=\"/static/htmx.1.9.11.js\"></script></head><body id=\"body\"><div id=\"layout\"><div id=\"navbar\" class=\"relative\"></div><div id=\"main\" style=\"min-height: calc(100svh - 64px);\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = comp.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
